apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: k8-ns
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 512Mi
    defaultRequest: # this section defines default requests
      cpu: 500m
      memory: 512Mi
    max: # max and min define the limit range
      cpu: 500m
      memory: 512Mi
    min:
      cpu: 200m
      memory: 256Mi
    type: Container
