apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mavenwebapprs
  labels:
    app: mavenwebappresource
  namespace: k8-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mavenwebapprs
  template:
    metadata:
      labels:
        app: mavenwebapprs
    spec:
      containers:
      - name: mavenwebapprs
        image: dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebapprs
  namespace: k8-ns
  labels:
    app: mavenwebapprs
spec:
  type: NodePort
  selector:
    app: mavenwebapprs
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30030
