apiVersion: v1
kind: ReplicationController
metadata:
  name: mavenwebapprc
  labels:
    app: mavenwebappresource
  namespace: k8-ns
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mavenwebapprc
    spec:
      containers:
      - name: mavenwebapprc
        image: dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebapprc
  namespace: k8-ns
  labels:
    app: mavenwebapprc
spec:
  type: NodePort
  selector:
    app: mavenwebapprc
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30030
