apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdp
  labels:
    app: mavenwebappdp
  namespace: k8-ns
spec:
  selector:
    matchLabels:
      app: mavenwebappdp
  template:
    metadata:
      labels:
        app: mavenwebappdp
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: mavenwebappdp
        image: salapalalokesh/maven-web-application:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 400m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: tomcatconfig
          mountPath: "/usr/local/tomcat/conf/tomcat-users.xml"
          subPath: "tomcat-users.xml"
      volumes:
      - name: tomcatconfig
        configMap:
          name: mavenwebappconfig
          items:
          - key: "tomcat-users.xml"
            path: "tomcat-users.xml"
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappdp
  namespace: k8-ns
  labels:
    app: mavenwebappdp
spec:
  type: NodePort
  selector:
    app: mavenwebappdp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30030

#  kubectl create secret docker-registry dockerhub --docker-username=salapalalokesh --docker-password=Lokesh@9192 -n k8-ns
# above command is used to create secret for Docker hub
# if it is nexus 
#  kubectl create secret docker-registry nexusrepo --docker-server=nexus.com --docker-username=salapalalokesh --docker-password=Lokesh@9192 -n k8-ns
